name: Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
#     - name: Deploy to Server 1
# #       uses: easingthemes/ssh-deploy@main
#       env:
#        SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
# #        REMOTE_HOST: ${ { secrets.HOST_DNS }}
# #        REMOTE_USER: ${ { secrets.USERNAME }}
# #        TARGET: ${ { secrets.TARGET_DIR }}
       
    - name: Run a multi-line script
      run: |
         mkdir ../build
         cp -TR . ../build
         tar -cvf deploy.tar ../build/
    
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: 'deploy.tar'
        target: '/home/ubuntu/'
        
    - name : copy php file 
      run: |
       tar -xvf deploy.tar
       sudo cp /home/ubuntu/build/index.php /var/www/html


