# Basic workflow to see Outputs
name: PHP 

# Running Workflow Manually
on:
  workflow_dispatch:
  repository_dispatch:    
    types: [on-demand-test]

jobs:
#Taking A Output "Hello" form a step and Storing it in OUTPUTS
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: testing the code
        uses: svikramjeet/git-action-laravel-phpunit@master
        
      - name: Build your code
        uses: Borodutch/build-and-lint-code@v1.0.3

    
        
