name: Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Server 1
#       uses: easingthemes/ssh-deploy@main
      env:
       SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
       REMOTE_HOST: ${ { secrets.HOST_DNS }}
       REMOTE_USER: ${ { secrets.USERNAME }}
       TARGET: ${ { secrets.TARGET_DIR }}
       
      run: |
       ssh -i ${ { secrets.EC2_SSH_KEY }} ubuntu@ec2-3-6-89-8.ap-south-1.compute.amazonaws.com

    
    
#     - name: copy file via ssh key
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         key: ${{ secrets.KEY }}
#         port: ${{ secrets.PORT }}
#         source: "index.php"
#         target: /var/www/html

